env: flex
runtime: nodejs

# [START env]
env_variables:
  PUBSUB_TOPIC: airquality
  # This token is used to verify that requests originate from your
  # application. It can be any sufficiently random string.
  PUBSUB_VERIFICATION_TOKEN: test
# [END env]
# [END app_yaml]
